[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
dependsOn = ['setup']
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120'

