[phases.setup]
nixPkgs = ['python311']

[phases.install]
dependsOn = ['setup']
cmds = [
    'python3 -m venv /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[start]
cmd = '. /opt/venv/bin/activate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120'

